### ISSUE TITLE
Possibility of migrating to futures-lite/smol-rs?

### ISSUE THREAD

**Issue by duplexsystem** [Bevy-Rust-GPU/rust-gpu-builder#2]
I think it would be a good idea to migrate to futures-lite/smol-rs in order to be consistent with bevy and reduce overall dependencies. Another idea would be it just use bevy_tasks (which uses futures-lite/smol-rs but has a lot of the boilerplate code already in it) but idk what your thoughts on depending directly on a bevy create is.

**Comment by ProfLander** [comment]
This repo is bevy-agnostic, so using `bevy_tasks` isn't an option.

I'm not sure I see the value in switching to a runtime crate for async, since the only current async dependency is the `futures` crate itself - the mentioned runtimes already build on top of that, so the main potential benefit would be in removing the `ctrlc` and `notify` dependencies in favour of runtime-specific interrupt handling and file watching.

Given that said runtimes pull in a litany of other dependencies to power other parts of the async ecosystem (I/O, networking, process management, etc), the proposition ends up as trading off two local dependencies for a bunch of upstream ones this crate doesn't use, so doesn't seem justifiable from that standpoint.

I played a bit of devil's advocate and had a poke around for parts of this crate that could benefit by being refactored around a runtime's higher-level async abstractions (and thus justify such a switch), but there aren't any that really stick out to me; everything relevant (like process management and filesystem handling) is black-boxed behind `spirv-builder`.

So I'm open to further argumentation - particularly if there are specific parts of the code that could be highlighted as benefitting from switching to a runtime - but as-is I don't think it's worth doing.

**Comment by duplexsystem** [comment]
The mentioned runtimes do not build off fututes, they build off fututes-lite and I wasn't really suggesting an async runtime more to just move to futures-lite instead of futures to reduce overall project (I.e. any projects using this and bevy) as fututes-lite is what bevy uses and this is bevy oriented

**Comment by ProfLander** [comment]
I see - that makes more sense. It looks like the various parts of smol can be pulled in piecemeal, which is more appealing than bringing in an entire runtime, and the "better-implemented futures" pitch of futures-lite is somewhat appealing.

However, `rust-gpu-builder` is a binary standalone tool rather than a dependency in the regular crates.io sense, so a slightly suboptimal set of async deps isn't going to waterfall down to any crates in projects that use it. And while it may be bevy-oriented in the practical sense, on a software design level it's purely a rust-gpu tool, so outside of "bevy's design choices are good" there's no causal line to be drawn between the two.

So I'd merge a pull request that swaps in `futures-lite` and the necessary `async-` crates with the appropriate code changes, but don't plan to actively pursue it myself on account of the cost : benefit ratio being very low compared to other active issues in the broader project.

**Comment by duplexsystem** [comment]
Ok if your willing to merge it I'll make a PR :)

**Comment by ProfLander** [comment]
A few new tasks have opened for this crate recently, so I sorted this out in the process of fixing them; `rust-gpu-builder` now uses `futures-lite`, `async-executor`, `async-channel` and `easy-parallel` instead of `futures`.

**Comment by duplexsystem** [comment]
This is great! And sorry I didn;t have time for a PR I was swamped with work :)
